config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'next', to: 'home#next'
  get 'prev', to: 'home#prev'
  get 'calendar', to: 'calendar#index'
  get 'prev_calendar', to: 'calendar#prev'
  get 'next_calendar', to: 'calendar#next'
  get 'slick', to: 'home#slick'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :get_date

  def index
  end

  def prev
    respond_to do |format|
      format.js
    end
  end

  def next
    respond_to do |format|
      format.js
    end
  end

  private
  def get_date
    @date = params[:date] ? Time.zone.parse(params[:date]).to_date : Date.current.to_date
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :get_date, only: [:prev, :next]
  def index
  end

  def prev
    respond_to do |format|
      format.html
      format.js
    end
  end

  def next
    respond_to do |format|
      format.html
      format.js
    end
  end

  def slick

  end

  private
  def get_date
    @date = params[:date] ? Time.zone.parse(params[:date]) : Date.current
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/calendar/_card.html.erb
<div class="card bg-light p-3">
  <h5 class="card-title"><%= date %></h5>
</div>

app/views/calendar/_next.html.erb
<div class="hideRight">
  <div class="card bg-light p-3">
    <h5 class="card-title"><%= date %></h5>
  </div>
</div>

app/views/calendar/_prev.html.erb
<div class="hideLeft">
  <div class="card bg-light p-3">
    <h5 class="card-title"><%= @date %></h5>
  </div>
</div>

app/views/calendar/index.html.erb
<%= link_to 'Home', root_path, clas: 'btn btn-primary' %>
<main>
  <div id='carousel'>
    <div class="hideLeft">
      <%= render 'card', date: @date - 4 %>
    </div>
    <div class="hideLeft">
      <%= render 'card', date: @date - 3 %>
    </div>
    <div class="hideLeft">
      <%= render 'card', date: @date - 2 %>
    </div>
    <div class="hideLeft">
      <%= render 'card', date: @date - 1 %>
    </div>
    <div class='selected'>
      <%= render 'card', date: @date %>
    </div>

    <div class='next'>
      <%= render 'card', date: @date + 1 %>
    </div>

    <div class="nextRightSecond">
      <%= render 'card', date: @date + 2 %>
    </div>

    <div class="hideRight">
      <%= render 'card', date: @date + 3 %>
    </div>
  </div>

  <div class="button-left">
    <div id='prev'>
      <
      <!-- <%= link_to '<', prev_calendar_path, remote: true %> -->
    </div>
  </div>
  <div class='button-right'>
    <div id='next'>
      >
      <!-- <%= link_to '>', next_calendar_path, remote: true %> -->
    </div>
  </div>
</main>

<script>
  function moveToSelected(element) {
    if (element == "next") {
      var selected = $(".selected").next();
    } else if (element == "prev") {
      var selected = $(".selected").prev();
    } else {
      var selected = element;
    }

    var next = $(selected).next();
    var prev = $(selected).prev();
    var prevSecond = $(prev).prev();
    var nextSecond = $(next).next();

    $(selected).removeClass().addClass("selected");

    $(next).removeClass().addClass("next");
    $(prev).removeClass().addClass('hideLeft');

    $(nextSecond).removeClass().addClass("nextRightSecond");
    $(prevSecond).removeClass().addClass('hideLeft');

    $(nextSecond).nextAll().removeClass().addClass('hideRight');
    $(prevSecond).prevAll().removeClass().addClass('hideLeft');
  }

  $(document).on('turbolinks:load', function() {
    $('#prev').click(function() {
      moveToSelected('prev');
    });

    $('#next').click(function() {
      moveToSelected('next');
    });
  })
</script>

app/views/calendar/next.js.erb
$("#carousel").append("<%= j render(partial: 'next', locals: { date: @date }) %>");

app/views/calendar/prev.js.erb
$("#carousel").prepend("<%= j render(partial: 'prev', locals: { date: @date }) %>");

app/views/home/_next.html.erb
<div class="hideRight">
  <div class="card bg-light p-3">
    <h5 class="card-title"><%= @date %></h5>
  </div>
</div>

app/views/home/index.html.erb
<%= link_to 'Calendar', calendar_path, clas: 'btn btn-primary' %>
<main>
  <div id='main-page'>
    <div id="carousel">
      <div class="hideLeft">
        <img src="https://s16.postimg.org/vklrwoxtx/cover9.jpg">
      </div>

      <div class="selected" data="<%= Date.current %>">
        <img src="https://s16.postimg.org/9drqcz611/cover1.jpg">
      </div>

      <div class="next" data="<%= Date.current + 1.day %>">
        <img src="https://s16.postimg.org/pnhwfvgp1/cover6.jpg">
      </div>

      <div class="nextRightSecond" data="<%= Date.current + 2.day %>">
        <img src="https://s16.postimg.org/edp6kxbnp/cover4.jpg">
      </div>
    </div>
  </div>

  <div class="button-left">
    <div id='prev'>
      <%= link_to '<', prev_path, remote: true %>
    </div>
  </div>
  <div class='button-right'>
    <div id='next'>
      <%= link_to '>', next_path, remote: true %>
    </div>
  </div>
  <div id='ajax'></div>
</main>

app/views/home/next.js.erb
$("#carousel").append("<%= j render(partial: 'next') %>");

app/views/home/prev.js.erb
$("#carousel").prepend("<%= j render(partial: 'prev') %>");

app/views/home/slick.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>
<style>
  .container {
    margin: 0 auto;
    padding: 40px;
    width: 80%;
    color: #333;
    background: #419be0;
  }

  .slick-slide {
    text-align: center;
    color: #419be0;
    background: white;
  }
</style>
<div class='pt-5'>
  <div class='container'>
    <div class='single-item'>
      <div><h3>1</h3></div>
      <div><h3>2</h3></div>
      <div><h3>3</h3></div>
      <div><h3>4</h3></div>
      <div><h3>5</h3></div>
      <div><h3>6</h3></div>
    </div>
  </div>
</div>

<script>
  $(".single-item").slick({
    centerMode: true,
    centerPadding: '60px',
    slidesToShow: 4,
    responsive: [
      {
        breakpoint: 768,
        settings: {
          arrows: false,
          centerMode: true,
          centerPadding: '40px',
          slidesToShow: 3
        }
      },
      {
        breakpoint: 480,
        settings: {
          arrows: false,
          centerMode: true,
          centerPadding: '40px',
          slidesToShow: 1
        }
      }
    ]
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App009CarouselCalendar</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>